"""Enums lifted verbatim from the client (Il2CppDumper output).

Generated by tools/gen_enums.py -- do not edit by hand.
Names colliding with Python keywords get a trailing underscore;
``name()`` still reports the original client spelling.
"""


class ClearType(object):
    Default = 0
    Fast = 1
    Immediate = 2
    Clear = 3

    _NAMES = {
        0: 'Default',
        1: 'Fast',
        2: 'Immediate',
        3: 'Clear',
    }

    @classmethod
    def name(cls, v):
        return cls._NAMES.get(v, str(v))


class MissionClearType(object):
    None_ = 0
    DailyMissionAllClear = 1
    WeeklyMissionAllClear = 2
    ItemUpgrade = 3
    FriendPoint = 4
    DimensionGapDailyPoint = 5
    DungeonClear = 6
    FamePoint = 7
    ArenaTier = 8
    Rankup = 9
    DimensionGachaOpenCount = 10
    EventGachaOpenCount = 11
    ContentsPlayCount = 12
    ContentsClearCount = 13
    AlienDetectCount = 14
    SceneCardGradeGetCount = 15
    ArtifactGradeGetCount = 16
    UnitGradeCount = 17
    TargetUnitGradeUp = 18
    TagArenaTier = 19
    GuildAttendanceCount = 20
    GuildDonationCount = 21
    SupportGuildResource = 22
    ArenaAttackWinPoint = 23
    BossDungeonGroupID = 24
    RankupAchievemen = 25
    WorldArenaTier = 26
    WorldArenaPlayPoint = 27
    UseResourceType1 = 28
    TargetUnitGradeUpAchievement = 29
    AddResourceType1 = 30
    AttendanceCount = 31
    BuyCashAccumulate = 32
    CheckCompleteMissionID = 33
    UnitLevelUp = 34
    AlienBossClearCount = 35
    GoodsUIDBuyCount = 36
    RequestGroupCompleteCount = 37
    SceneCardGradeRecvCount = 38
    ArtifactGradeRecvCount = 39
    ItemGradeRecvCount = 40
    DailyClearCount = 41
    WeeklyClearCount = 42
    JoinSpecificTime = 43
    AwakenPartsSlotID = 44
    DungeonClearAchieve = 45
    TotalUnitLevelUp = 46
    TagArenaAttackWinPoint = 47
    UnitRareness = 48
    ConnectSocialAccount = 49
    HeartHeaterChapterClear = 50
    WorldRaidMultiPlay = 51
    DungeonClearCountGroup = 52
    ContentsClearCountGroup = 53
    ContentsPlayCountGroup = 54
    AutoPlayRewardCount = 55
    AwakenPartsSlotIDMission = 56
    TotalUnitLevelUpMission = 57
    ClearAnyMissionInGroup = 58
    TotalDamageRewardCount = 59
    CurrentResourceAmount = 60
    MultiCondition_ClearAny = 61
    MultiCondition_ClearAll = 62
    GetSpecificUnitOnlyGacha = 63
    UnitEquipAtSpecificSlot = 64
    UnitSpecificAwaken = 65
    WaveRaidHighestScore = 66
    GlobalArenaPlayPoint = 67
    UnitAwakenPassiveBonusStat = 68
    RelayMissionTotalClear = 69
    ChoiceSceneCardEventOpenCount = 70
    ArtifactLvUpCount = 71
    ArtifactMaxLvUpCount = 72
    PaidUnitGachaCount = 73
    WaveRaid2HighestScore = 74

    _NAMES = {
        0: 'None',
        1: 'DailyMissionAllClear',
        2: 'WeeklyMissionAllClear',
        3: 'ItemUpgrade',
        4: 'FriendPoint',
        5: 'DimensionGapDailyPoint',
        6: 'DungeonClear',
        7: 'FamePoint',
        8: 'ArenaTier',
        9: 'Rankup',
        10: 'DimensionGachaOpenCount',
        11: 'EventGachaOpenCount',
        12: 'ContentsPlayCount',
        13: 'ContentsClearCount',
        14: 'AlienDetectCount',
        15: 'SceneCardGradeGetCount',
        16: 'ArtifactGradeGetCount',
        17: 'UnitGradeCount',
        18: 'TargetUnitGradeUp',
        19: 'TagArenaTier',
        20: 'GuildAttendanceCount',
        21: 'GuildDonationCount',
        22: 'SupportGuildResource',
        23: 'ArenaAttackWinPoint',
        24: 'BossDungeonGroupID',
        25: 'RankupAchievemen',
        26: 'WorldArenaTier',
        27: 'WorldArenaPlayPoint',
        28: 'UseResourceType1',
        29: 'TargetUnitGradeUpAchievement',
        30: 'AddResourceType1',
        31: 'AttendanceCount',
        32: 'BuyCashAccumulate',
        33: 'CheckCompleteMissionID',
        34: 'UnitLevelUp',
        35: 'AlienBossClearCount',
        36: 'GoodsUIDBuyCount',
        37: 'RequestGroupCompleteCount',
        38: 'SceneCardGradeRecvCount',
        39: 'ArtifactGradeRecvCount',
        40: 'ItemGradeRecvCount',
        41: 'DailyClearCount',
        42: 'WeeklyClearCount',
        43: 'JoinSpecificTime',
        44: 'AwakenPartsSlotID',
        45: 'DungeonClearAchieve',
        46: 'TotalUnitLevelUp',
        47: 'TagArenaAttackWinPoint',
        48: 'UnitRareness',
        49: 'ConnectSocialAccount',
        50: 'HeartHeaterChapterClear',
        51: 'WorldRaidMultiPlay',
        52: 'DungeonClearCountGroup',
        53: 'ContentsClearCountGroup',
        54: 'ContentsPlayCountGroup',
        55: 'AutoPlayRewardCount',
        56: 'AwakenPartsSlotIDMission',
        57: 'TotalUnitLevelUpMission',
        58: 'ClearAnyMissionInGroup',
        59: 'TotalDamageRewardCount',
        60: 'CurrentResourceAmount',
        61: 'MultiCondition_ClearAny',
        62: 'MultiCondition_ClearAll',
        63: 'GetSpecificUnitOnlyGacha',
        64: 'UnitEquipAtSpecificSlot',
        65: 'UnitSpecificAwaken',
        66: 'WaveRaidHighestScore',
        67: 'GlobalArenaPlayPoint',
        68: 'UnitAwakenPassiveBonusStat',
        69: 'RelayMissionTotalClear',
        70: 'ChoiceSceneCardEventOpenCount',
        71: 'ArtifactLvUpCount',
        72: 'ArtifactMaxLvUpCount',
        73: 'PaidUnitGachaCount',
        74: 'WaveRaid2HighestScore',
    }

    @classmethod
    def name(cls, v):
        return cls._NAMES.get(v, str(v))


class ResourceType(object):
    NONE = -1
    Gold = 0
    Unit = 1
    LvUpMet = 2
    TierUpMet = 3
    CharEXP = 4
    Item = 5
    Rune = 6
    RuneUpMet = 7
    Artifact = 8
    AritfactUpMet = 9
    EvolMet = 12
    GroupSplit = 13
    CommanderLvUpMet = 14
    CommanderSkillUpMet = 15
    UnitPieces = 16
    RandomUnitPieces = 17
    ResourceUnit = 18
    Cash = 19
    EventCash = 20
    TotalCash = 21
    FriendPoint = 22
    Commander = 23
    SkillBook = 24
    HeroCoin = 25
    HeroDungeonTicket = 26
    BGMRes = 27
    TrainingTowerTicket = 28
    TrainingTowerStage = 29
    ArenaTicket = 30
    RequestCount = 31
    DimensionGachaTimeReduce = 32
    DimensionGachaTimeReset = 33
    AlienDetectMonCount = 34
    AlienCount = 35
    RoguelikeStatPoint = 36
    RoguelikeInstantPoint = 37
    RoguelikeInstantItem = 38
    AlienTicket = 39
    DummyGuildDonationCoin = 40
    DummyGuildContribution = 41
    SceneCard = 42
    Profile = 43
    SceneCardPack = 44
    GachaCoin = 45
    RequestPoint = 46
    UnitPiecePack = 47
    ItemRandomBox = 48
    MedalPoint = 49
    TimeRewardGold = 50
    TimeRewardLvUpMet = 52
    TimeRewardTierUpMet = 53
    TimeRewardCharEXP = 54
    TimeRewardItem = 55
    TimeRewardRequestPoint = 56
    TimeRewardCristalUpMet = 57
    TimeRewardAritfact = 58
    TimeRewardAritfactUpMet = 59
    TimeRewardRandomBox = 60
    TimeRewardCommandCenterExp = 61
    TimeRewardEnd = 99
    Unit_Inven_Max = 100
    Cristal_Inven_Max = 101
    Artifact_Inven_Max = 102
    Res_Inven_Max = 103
    ScendCard_Inven_Max = 104
    Accessory_Inven_Max = 105
    FamePoint = 110
    RelationPoint = 111
    CubeReward = 112
    CashBoxReward = 113
    PremiumUnitMaterial = 114
    PremiumUnitCommonMaterial = 115
    QuestRoguelikePlayCount = 116
    FriendDeleteCount = 117
    FriendPointMaxRecvCount = 118
    EventCoin = 119
    ItemRandomBoxInven = 120
    SceneCardSlotImmediateCommit = 121
    SceneCardManufactureMaterial = 122
    HardDungeonTicket = 123
    GuildRaidOpenTicket = 124
    ArenaSeasonCoin = 125
    OrdealTowerTicket = 126
    ArtifactMaterial = 127
    TagArenaTicket = 128
    TotalDungeonTicket = 129
    UnitSkillLevelUpMeterial = 130
    BossArtifactMeterial = 131
    GuildCoin = 132
    GuildExchangeCoinLimit = 133
    EventDungeonTicket = 134
    EventSummonMaterial = 135
    WorldArenaTicket = 136
    Accessory = 137
    AccessoryStatChangeTicket = 138
    SelectBox = 139
    GachaEventTicket = 143
    UnitRarenessUpgradeTicket = 144
    HeroPassEventClearTicket = 145
    HeroPassEventPoint = 146
    HeroRecallTicket = 147
    GuildDonation = 148
    GuildWarCoin = 149
    AccessSupport = 150
    SelectGacha = 151
    GachaTicketCollabo = 152
    HeroSkin = 153
    ArtifactGrowupMaterial = 154
    SkinGems = 155
    HeartHeaterCoin = 156
    WorldRaidTicket = 157
    WallPaper = 158
    QuestPoint_Daily = 159
    ArtifactRandChangeTicket = 160
    SceneCardManufacture = 161
    QuestPoint_Weekly = 162
    GachaEvent2_Ticket = 163
    StoryTreasureBox = 164
    CommandCenterExp = 165
    Commanders_LvUp_Material = 166
    GachaCoupon = 167
    CollaboRepeatDungeonTicket = 168
    CollaboRepeatDungeonPoint = 169
    Frame = 170
    ArenaMatchUserReset = 171
    SceneCardPiece = 172
    BingoTicket = 173
    ImmediatelyClearTicket = 174
    JumpingUpTicket = 175
    EquipItemEnhanceMaterialItem = 176
    MiniGameDungeonTicket = 177
    MiniGame2Ticket = 178
    MiniGame3Ticket = 179
    MiniGame4Ticket = 180
    WhaleBossTicket = 181
    MiniGameRPSTicket = 182
    ComebackHeroPassPoint = 183
    ComebackHeroPassCubeTicket = 184
    MiniGame4Ticket2 = 185
    MiniGameBaseBallTicket = 186

    _NAMES = {
        -1: 'NONE',
        0: 'Gold',
        1: 'Unit',
        2: 'LvUpMet',
        3: 'TierUpMet',
        4: 'CharEXP',
        5: 'Item',
        6: 'Rune',
        7: 'RuneUpMet',
        8: 'Artifact',
        9: 'AritfactUpMet',
        12: 'EvolMet',
        13: 'GroupSplit',
        14: 'CommanderLvUpMet',
        15: 'CommanderSkillUpMet',
        16: 'UnitPieces',
        17: 'RandomUnitPieces',
        18: 'ResourceUnit',
        19: 'Cash',
        20: 'EventCash',
        21: 'TotalCash',
        22: 'FriendPoint',
        23: 'Commander',
        24: 'SkillBook',
        25: 'HeroCoin',
        26: 'HeroDungeonTicket',
        27: 'BGMRes',
        28: 'TrainingTowerTicket',
        29: 'TrainingTowerStage',
        30: 'ArenaTicket',
        31: 'RequestCount',
        32: 'DimensionGachaTimeReduce',
        33: 'DimensionGachaTimeReset',
        34: 'AlienDetectMonCount',
        35: 'AlienCount',
        36: 'RoguelikeStatPoint',
        37: 'RoguelikeInstantPoint',
        38: 'RoguelikeInstantItem',
        39: 'AlienTicket',
        40: 'DummyGuildDonationCoin',
        41: 'DummyGuildContribution',
        42: 'SceneCard',
        43: 'Profile',
        44: 'SceneCardPack',
        45: 'GachaCoin',
        46: 'RequestPoint',
        47: 'UnitPiecePack',
        48: 'ItemRandomBox',
        49: 'MedalPoint',
        50: 'TimeRewardGold',
        52: 'TimeRewardLvUpMet',
        53: 'TimeRewardTierUpMet',
        54: 'TimeRewardCharEXP',
        55: 'TimeRewardItem',
        56: 'TimeRewardRequestPoint',
        57: 'TimeRewardCristalUpMet',
        58: 'TimeRewardAritfact',
        59: 'TimeRewardAritfactUpMet',
        60: 'TimeRewardRandomBox',
        61: 'TimeRewardCommandCenterExp',
        99: 'TimeRewardEnd',
        100: 'Unit_Inven_Max',
        101: 'Cristal_Inven_Max',
        102: 'Artifact_Inven_Max',
        103: 'Res_Inven_Max',
        104: 'ScendCard_Inven_Max',
        105: 'Accessory_Inven_Max',
        110: 'FamePoint',
        111: 'RelationPoint',
        112: 'CubeReward',
        113: 'CashBoxReward',
        114: 'PremiumUnitMaterial',
        115: 'PremiumUnitCommonMaterial',
        116: 'QuestRoguelikePlayCount',
        117: 'FriendDeleteCount',
        118: 'FriendPointMaxRecvCount',
        119: 'EventCoin',
        120: 'ItemRandomBoxInven',
        121: 'SceneCardSlotImmediateCommit',
        122: 'SceneCardManufactureMaterial',
        123: 'HardDungeonTicket',
        124: 'GuildRaidOpenTicket',
        125: 'ArenaSeasonCoin',
        126: 'OrdealTowerTicket',
        127: 'ArtifactMaterial',
        128: 'TagArenaTicket',
        129: 'TotalDungeonTicket',
        130: 'UnitSkillLevelUpMeterial',
        131: 'BossArtifactMeterial',
        132: 'GuildCoin',
        133: 'GuildExchangeCoinLimit',
        134: 'EventDungeonTicket',
        135: 'EventSummonMaterial',
        136: 'WorldArenaTicket',
        137: 'Accessory',
        138: 'AccessoryStatChangeTicket',
        139: 'SelectBox',
        143: 'GachaEventTicket',
        144: 'UnitRarenessUpgradeTicket',
        145: 'HeroPassEventClearTicket',
        146: 'HeroPassEventPoint',
        147: 'HeroRecallTicket',
        148: 'GuildDonation',
        149: 'GuildWarCoin',
        150: 'AccessSupport',
        151: 'SelectGacha',
        152: 'GachaTicketCollabo',
        153: 'HeroSkin',
        154: 'ArtifactGrowupMaterial',
        155: 'SkinGems',
        156: 'HeartHeaterCoin',
        157: 'WorldRaidTicket',
        158: 'WallPaper',
        159: 'QuestPoint_Daily',
        160: 'ArtifactRandChangeTicket',
        161: 'SceneCardManufacture',
        162: 'QuestPoint_Weekly',
        163: 'GachaEvent2_Ticket',
        164: 'StoryTreasureBox',
        165: 'CommandCenterExp',
        166: 'Commanders_LvUp_Material',
        167: 'GachaCoupon',
        168: 'CollaboRepeatDungeonTicket',
        169: 'CollaboRepeatDungeonPoint',
        170: 'Frame',
        171: 'ArenaMatchUserReset',
        172: 'SceneCardPiece',
        173: 'BingoTicket',
        174: 'ImmediatelyClearTicket',
        175: 'JumpingUpTicket',
        176: 'EquipItemEnhanceMaterialItem',
        177: 'MiniGameDungeonTicket',
        178: 'MiniGame2Ticket',
        179: 'MiniGame3Ticket',
        180: 'MiniGame4Ticket',
        181: 'WhaleBossTicket',
        182: 'MiniGameRPSTicket',
        183: 'ComebackHeroPassPoint',
        184: 'ComebackHeroPassCubeTicket',
        185: 'MiniGame4Ticket2',
        186: 'MiniGameBaseBallTicket',
    }

    @classmethod
    def name(cls, v):
        return cls._NAMES.get(v, str(v))


class SceneType(object):
    ENone = -1
    EResourceUpdate = 0
    EAuth = 1
    ECheat = 2
    EAwakenTree = 3
    EMenu = 4
    EDungeonList = 5
    EDungeonTeamSetting = 6
    EDungeonPlay = 7
    EUnitList = 8
    EUnitDetail = 9
    EUnitSkillDetail = 10
    ECommander = 11
    EHeroDungeon = 12
    EHeroDungeonTeamSetting = 13
    EPvP = 14
    EHeroDungeonPlay = 15
    EDungeonScenarioReview = 16
    ETrainingTowerPlay = 17
    EInventory = 18
    ETrainingTowerDungeon = 19
    ETrainingTowerDungeonTeamSetting = 20
    EDimentionGapStageSelect = 21
    EDimentionGapTeamSelect = 22
    EDimentionGapPlay = 23
    EPvPEntrance = 24
    EPvPDefenseTemSetting = 25
    EPvPAttackTemSetting = 26
    EPvPReady = 27
    RhythmDungeonPlay = 28
    RhythmDungeonTeamSelect = 29
    RhythmDungeonStageSelect = 30
    EDimensionGacha = 31
    EWorldScene = 32
    EPVPReplayScene = 33
    EAlienPlayScene = 34
    EAlienDungeonTeamSetting = 35
    EHeartHeaterMain = 36
    EHeartHeaterTeamSetting = 37
    EHeartHeaterPlay = 38
    ERoguelikeMission = 39
    EGuildList = 40
    EGuildMain = 41
    UnitDetailSkillTree = 42
    EWorldPackmanScenePrefab = 43
    EStore = 44
    EDimensionGachaStore = 45
    EHeroDungeonShop = 46
    ETutorial = 47
    ETutorialPlay = 48
    EDimensionGachaPremiumHeroSummon = 49
    EHeartHeaterSelect = 50
    FriendAttackTeamSelectScene = 51
    FriendPvPScene = 52
    EWorldCollectionBook = 53
    EHardDungeonTeamSetting = 54
    EHardDungeonPlay = 55
    EGuildDungeonTeamSetting = 56
    EGuildDungeonPlay = 57
    EDimensionBlackSmith = 58
    EOrdealDungeonStageSelect = 59
    EOrdealDungeonTeamSetting = 60
    EOrdealDungeonPlay = 61
    EORdealTowerShop = 62
    ETagArenaPlay = 63
    ETagArenaEntrance = 64
    ETagArenaDefenseTeamSetting = 65
    ETagArenaAttackTeamSetting = 66
    ETagArenaReady = 67
    EBossDungeonPlay = 68
    EBossDungeonTeamSetting = 69
    EBossDungeonStageSelect = 70
    ETagArenaReplay = 71
    EHeroDungeonChapterSelect = 72
    EEventDungeonTeamSetting = 73
    EEventDungeonPlayScene = 74
    EWorldArenaEntrance = 75
    EWorldArenaTeamSetting = 76
    EWorldArenaMatchTeamSetting = 77
    EWorldArenaPlay = 78
    EWorldArenaReplayScene = 79
    EWorldAIArenaPlay = 80
    EWorldRaidMain = 81
    EWorldRaidSingleTeamSetting = 82
    EWorldRaidPartyMatchSetting = 83
    EWorldRaidPartyTeamSetting = 84
    EWorldRaidSinglePlay = 85
    EWorldRaidMultyPlay = 86
    EWorldShop = 87
    EGuildWarsDefenseTeamSetting = 88
    EGuildWarsAttackTeamSetting = 89
    EGuildWarsPvpPlay = 90
    EGuildWarsPvePlay = 91
    EGuildWarsEntrance = 92
    EContentsRanking = 93
    ESkinShop = 94
    EUnitDetailSkin = 95
    ETotalDamageDungeonPlay = 96
    ETotalDamageDungeonTeamSetting = 97
    ETotalDamageDungeonStageSelect = 98
    ECommandCenterScene = 99
    ECommandersInfoScene = 100
    ECollaboDungeonTeamSetting = 101
    ECollaboDungeonPlay = 102
    ECollaboRepeatDungeonTeamSetting = 103
    ECollaboRepeatDungeonPlay = 104
    EWaveRaidEntrance = 105
    EWaveRaidTeamSelect = 106
    EWaveRaidPlay = 107
    EGlobalArenaEntrance = 108
    EGlobalArenaReady = 109
    EGlobalArenaPreBan = 110
    EGlobalArenaTeamSelect = 111
    EGlobalArenaTeamSetting = 112
    ECostumeGachaPreview = 113
    EGlobalArenaPlay = 114
    ENewHeroEvent = 115
    EEventDungeonMiniGame = 116
    EEventMiniGameIceFishing = 117
    EECubeDungeonPlay = 118
    EECubeDungeonListScene = 119
    EECubeDungeonShopScene = 120
    EECubeDungeonTeamSelectScene = 121
    EHephaiForgeEventScene = 122
    ETemp = 123
    EWaveRaid2Entrance = 124
    EWaveRaid2BossSelect = 125
    EWaveRaid2TeamSelect = 126
    EWaveRaid2DungeonPlay = 127
    EMiniGameBaseball = 128
    Max = 129

    _NAMES = {
        -1: 'ENone',
        0: 'EResourceUpdate',
        1: 'EAuth',
        2: 'ECheat',
        3: 'EAwakenTree',
        4: 'EMenu',
        5: 'EDungeonList',
        6: 'EDungeonTeamSetting',
        7: 'EDungeonPlay',
        8: 'EUnitList',
        9: 'EUnitDetail',
        10: 'EUnitSkillDetail',
        11: 'ECommander',
        12: 'EHeroDungeon',
        13: 'EHeroDungeonTeamSetting',
        14: 'EPvP',
        15: 'EHeroDungeonPlay',
        16: 'EDungeonScenarioReview',
        17: 'ETrainingTowerPlay',
        18: 'EInventory',
        19: 'ETrainingTowerDungeon',
        20: 'ETrainingTowerDungeonTeamSetting',
        21: 'EDimentionGapStageSelect',
        22: 'EDimentionGapTeamSelect',
        23: 'EDimentionGapPlay',
        24: 'EPvPEntrance',
        25: 'EPvPDefenseTemSetting',
        26: 'EPvPAttackTemSetting',
        27: 'EPvPReady',
        28: 'RhythmDungeonPlay',
        29: 'RhythmDungeonTeamSelect',
        30: 'RhythmDungeonStageSelect',
        31: 'EDimensionGacha',
        32: 'EWorldScene',
        33: 'EPVPReplayScene',
        34: 'EAlienPlayScene',
        35: 'EAlienDungeonTeamSetting',
        36: 'EHeartHeaterMain',
        37: 'EHeartHeaterTeamSetting',
        38: 'EHeartHeaterPlay',
        39: 'ERoguelikeMission',
        40: 'EGuildList',
        41: 'EGuildMain',
        42: 'UnitDetailSkillTree',
        43: 'EWorldPackmanScenePrefab',
        44: 'EStore',
        45: 'EDimensionGachaStore',
        46: 'EHeroDungeonShop',
        47: 'ETutorial',
        48: 'ETutorialPlay',
        49: 'EDimensionGachaPremiumHeroSummon',
        50: 'EHeartHeaterSelect',
        51: 'FriendAttackTeamSelectScene',
        52: 'FriendPvPScene',
        53: 'EWorldCollectionBook',
        54: 'EHardDungeonTeamSetting',
        55: 'EHardDungeonPlay',
        56: 'EGuildDungeonTeamSetting',
        57: 'EGuildDungeonPlay',
        58: 'EDimensionBlackSmith',
        59: 'EOrdealDungeonStageSelect',
        60: 'EOrdealDungeonTeamSetting',
        61: 'EOrdealDungeonPlay',
        62: 'EORdealTowerShop',
        63: 'ETagArenaPlay',
        64: 'ETagArenaEntrance',
        65: 'ETagArenaDefenseTeamSetting',
        66: 'ETagArenaAttackTeamSetting',
        67: 'ETagArenaReady',
        68: 'EBossDungeonPlay',
        69: 'EBossDungeonTeamSetting',
        70: 'EBossDungeonStageSelect',
        71: 'ETagArenaReplay',
        72: 'EHeroDungeonChapterSelect',
        73: 'EEventDungeonTeamSetting',
        74: 'EEventDungeonPlayScene',
        75: 'EWorldArenaEntrance',
        76: 'EWorldArenaTeamSetting',
        77: 'EWorldArenaMatchTeamSetting',
        78: 'EWorldArenaPlay',
        79: 'EWorldArenaReplayScene',
        80: 'EWorldAIArenaPlay',
        81: 'EWorldRaidMain',
        82: 'EWorldRaidSingleTeamSetting',
        83: 'EWorldRaidPartyMatchSetting',
        84: 'EWorldRaidPartyTeamSetting',
        85: 'EWorldRaidSinglePlay',
        86: 'EWorldRaidMultyPlay',
        87: 'EWorldShop',
        88: 'EGuildWarsDefenseTeamSetting',
        89: 'EGuildWarsAttackTeamSetting',
        90: 'EGuildWarsPvpPlay',
        91: 'EGuildWarsPvePlay',
        92: 'EGuildWarsEntrance',
        93: 'EContentsRanking',
        94: 'ESkinShop',
        95: 'EUnitDetailSkin',
        96: 'ETotalDamageDungeonPlay',
        97: 'ETotalDamageDungeonTeamSetting',
        98: 'ETotalDamageDungeonStageSelect',
        99: 'ECommandCenterScene',
        100: 'ECommandersInfoScene',
        101: 'ECollaboDungeonTeamSetting',
        102: 'ECollaboDungeonPlay',
        103: 'ECollaboRepeatDungeonTeamSetting',
        104: 'ECollaboRepeatDungeonPlay',
        105: 'EWaveRaidEntrance',
        106: 'EWaveRaidTeamSelect',
        107: 'EWaveRaidPlay',
        108: 'EGlobalArenaEntrance',
        109: 'EGlobalArenaReady',
        110: 'EGlobalArenaPreBan',
        111: 'EGlobalArenaTeamSelect',
        112: 'EGlobalArenaTeamSetting',
        113: 'ECostumeGachaPreview',
        114: 'EGlobalArenaPlay',
        115: 'ENewHeroEvent',
        116: 'EEventDungeonMiniGame',
        117: 'EEventMiniGameIceFishing',
        118: 'EECubeDungeonPlay',
        119: 'EECubeDungeonListScene',
        120: 'EECubeDungeonShopScene',
        121: 'EECubeDungeonTeamSelectScene',
        122: 'EHephaiForgeEventScene',
        123: 'ETemp',
        124: 'EWaveRaid2Entrance',
        125: 'EWaveRaid2BossSelect',
        126: 'EWaveRaid2TeamSelect',
        127: 'EWaveRaid2DungeonPlay',
        128: 'EMiniGameBaseball',
        129: 'Max',
    }

    @classmethod
    def name(cls, v):
        return cls._NAMES.get(v, str(v))


class NMError(object):
    None_ = 0
    Error_Invisible = 999
    Error_CheckTierUpNoneTierInfo = 1000
    Error_CheckTierUpGrade = 1001
    Error_CheckTierUpResource1 = 1002
    Error_CheckTierUpResource2 = 1003
    Error_CheckTierUpResource3 = 1004
    Error_CheckLevelUpNoneLevelupInfo = 1005
    Error_CheckLevelUpResource1 = 1006
    Error_CheckLevelUpResource2 = 1007
    Error_CheckGradeUpNoneGradeUpInfo = 1008
    Error_CheckGradeUPMaxTier = 1009
    Error_CheckGradeUpMaxLevel = 1010
    Error_CheckGradeUpResource1 = 1011
    Error_CheckGradeUpResource2 = 1012
    Error_CheckGradeUpResource3 = 1013
    Error_CheckAwakenNoneAwakenInfo = 1014
    Error_CheckAwakenResource1 = 1015
    Error_CheckAwakenResource2 = 1016
    Error_CheckAwakenResource3 = 1017
    Error_CheckAwakenResource4 = 1018
    Error_CheckAwakenResource5 = 1019
    Error_CheckUpgradeItemNoneUpgradeItemInfo = 1020
    Error_CheckUpgradeItemResource1 = 1021
    Error_CheckUpgradeItemResource2 = 1022
    Error_CheckUpgradeItemResource3 = 1023
    Error_CheckUpgradeItemResource4 = 1024
    Error_CheckUpgradeItemResource5 = 1025
    Error_CheckUpgradeItemResource6 = 1026
    Error_CheckArtifactLevelUpNoneInfo = 1027
    Error_CheckArtifactTierUpNoneInfo = 1028
    Error_CheckArtifactTierUpLowerExp = 1029
    Error_CheckArtifactTierUpResource1 = 1030
    Error_CheckArtifactTierUpResource2 = 1031
    Error_CheckRuneGradeUpNoneGradeUpInfo = 1032
    Error_CheckRuneGradeUpResource1 = 1033
    Error_CheckRuneGradeUpResource2 = 1034
    Error_CheckRuneFixGradeUpNoneGradeUpInfo = 1035
    Error_CheckRuneFixGradeUpResource1 = 1036
    Error_CheckRuneChangeNoneChangeInfo = 1037
    Error_CheckRuneChangeResource1 = 1038
    Error_CheckRuneChangeResource2 = 1039
    Error_CheckSkillBookLean = 1040
    Error_CheckSkillBookDontLean = 1041
    Error_CheckSkillBookNotLean = 1042
    Error_CheckSkillBookMaxGrade = 1043
    Error_CheckSkillBookNoneInfo = 1044
    Error_CheckSkillBookResource = 1045
    Error_CommanderMaxLevel = 1046
    Error_CommanderNotMaxLevel = 1047
    Error_CommanderNoneLevelupInfo = 1048
    Error_CommanderMaxTier = 1049
    Error_CommanderNoneTierupInfo = 1050
    Error_CommanderCost = 1051
    Error_CommanderLeanBGM = 1052
    Error_CommanderNotLeanBGM = 1053
    Error_CommanderNoneBGMInfo = 1054
    Error_CommanderNoneBGMLearnInfo = 1055
    Error_CommanderNoneBGMGradeUpInfo = 1056
    Error_CommanderBGMMaxGrade = 1057
    Error_CommanderNonePassiveInfo = 1058
    Error_CommanderPassiveMaxLevel = 1059
    Error_NotOpenDungeon = 1060
    Error_TimeOverDungeon = 1061
    Error_InvaildDungeon = 1062
    Error_ClearedDungeon = 1063
    Error_RequirePrevDungeonClear = 1064
    Error_LowUserRankDungeon = 1065
    Error_TraningTowerNotSaveCheckPoint = 1066
    Error_ArtifactLevelUpExpOverFlow = 1067
    Error_GachaClose = 1068
    Error_InvaildGachaInfo = 1069
    Error_CheckGachaResource = 1070
    Error_CheckTimeReduceResourceNotEnough = 1071
    Error_CheckTimeReduceOver = 1072
    ErrorRequestEnoughtUnitCount = 1073
    Error_CheckSellAble = 1074
    Error_UnitNoneSelectItem = 1075
    Error_FriendPointSendLackOfTime = 1076
    Error_ChangePartyUnchangeableUnit = 1079
    Error_ChangePartyLimitChangeUnit = 1080
    Error_ChangePartyFull = 1081
    Error_ChangePartyDuplicateUnit = 1082
    Error_NotFullParty = 1083
    Error_CheckGradeUpMaxGrade = 1084
    Error_CheckAwakenLean = 1085
    Error_CheckAwakenNotConditionClear = 1086
    Error_CheckAwakenSelectDontLean = 1087
    Error_CheckAwakenSelectCost = 1088
    Error_NotUpdate = 1089
    Error_GuildDonationLimitOnceDay = 1090
    Error_GuildDonationNotEnoughtResource = 1091
    Error_CheckAwakenRewardConditionNoneInfo = 1092
    Error_CheckAwakenRewardConditionOverIndex = 1093
    Error_CheckAwakenRewardConditionGetIndex = 1094
    Error_CheckAwakenRewardConditionDontCondition = 1095
    Error_CheckSceneCardLevelupNoneTargetInfo = 1096
    Error_CheckSceneCardLevelupNonePreMaterialInfo = 1097
    Error_CheckSceneCardLevelupNoneCurrentMaterialInfo = 1098
    Error_CheckSceneCardLevelupMaxSkillLevel = 1099
    Error_CheckSceneCardLevelupMaxLevel = 1100
    Error_CheckSceneCardLevelupGold = 1101
    Error_CheckSceneCardEquipSameID = 1102
    Error_MaterialSceneCardVaildEquipUnitUID = 1103
    Error_SceneCardEnhanceEmptyMaterial = 1104
    Error_CheckSceneCardMaxLevelOnlyDuplicateCard = 1105
    Warning_CheckSceneCardMaxSkillLevelAddDuplicateCard = 1106
    Error_CheckSceneCardEquipNoneInfo = 1107
    Error_CheckSceneCardEquipCondition = 1108
    Error_CheckSceneCardEquipUsed = 1109
    Error_CheckSceneCardLevelupEquip = 1110
    Error_CheckSceneCardEquipSlot = 1111
    Error_MyInfoChangeProfileSendPacket = 1112
    Error_MyInfoChangeProfileNotSelect = 1113
    Error_MyInfoChangeProfileSameProfile = 1114
    Error_MyInfoChangeNickNameCost = 1115
    Error_MyInfoChangeNickNameLength = 1116
    Error_TrainingTowerJoinCount0 = 1117
    Error_CheckGradeUpNotNextGrade = 1118
    Error_CheckLevelUpUserRank = 1119
    Error_SummonHeroPieceNotEnough = 1120
    Error_PerchasingGetPerchasingInfo = 1121
    Error_PerchasingnotAvailableForpurChase = 1122
    Error_PerchasingInitialized = 1123
    Error_NotPieceDecompositionEnoughtResource = 1128
    Error_EtcSellNotEnoughResource = 1129
    Error_NotWeaponSellEnoughResource = 1130
    Error_PremiumHeroSummonNotEnoughResource = 1131
    Error_InvaildHeroPieceSummon = 1132
    PackmanResetNotEnoughCost = 1133
    PackmanLevelUpNotEnoughCost = 1134
    NotEnoughNPCRequestRenew = 1135
    NotEnoughHeroDungeonJoinCost = 1137
    NotEnoughTrainingTowerDungeonJoinCost = 1138
    Error_NotEnoughDimensionGachaInstantCost = 1139
    NotEnoughAlienDungeonJoinCost = 1140
    NotEnoughAlienDungeonTicket = 1141
    GuildRaidOnlyGuildMasterCanOpen = 1142
    GuildRaidOnlyGuildMasterCanReOpen = 1143
    Error_CheckSceneCardEquipConditionFailUnitForce = 1144
    Error_CheckSceneCardEquipConditionFailUnitClass = 1145
    Error_CheckSceneCardEquipConditionFailUnitGrade = 1146
    Error_CheckSceneCardEquipConditionFailUnitType = 1147
    Error_CheckSceneCardEquipConditionFailUnitID = 1148
    Error_PerchasingProgress = 1149
    Error_CheckGuildRaidNotEnoughtTicket = 1150
    Error_SceneCardEnhanceFull10Material = 1151
    EventSceneCardMaximunTrade = 1152
    EventSceneCardNotEnoughtCost = 1153
    Error_SceneCardSellVaildEquipUnitUID = 1154
    NotEnoughOrdealDungeonJoinCost = 1155
    Error_SelectOrdealDugenonStage = 1156
    Error_RequirePreOrdealDungeonClear = 1157
    Error_SelectPreOrdealDugenonStage = 1158
    Error_MaterialArtifactVaildEquipUnitUID = 1159
    Error_ArtifactEnhanceFull10Material = 1160
    Error_ArtifactSellVaildEquipUnitUID = 1161
    Error_WaitRewardNotOngoingOrdealDungeon = 1162
    Error_ArtifactEnhanceMaxLevelOverExp = 1163
    Error_GetWaitRewardAfterReceiveClearReward = 1164
    Error_NotEnoughtBossDungeonTicket = 1165
    Error_CheckSceneCardEquipConditionFailElement = 1166
    Error_SelectMaterialArtifact = 1167
    Error_CloseGoods = 1168
    Error_RequirePreBossDungeonClear = 1169
    Error_NotEnoughtStoryDungeonJoinCost = 1170
    Error_NotEnoughMedalPoint = 1171
    ErrorTagArenaEmptyParty = 1172
    Error_BossArtifactNotEnoughtCost = 1173
    Error_DuplicateHeroExtiatParties = 1174
    Error_GuildShopAlreadyMaxLevel = 1175
    Error_GuildShopLevelUpFailed_LowGuildLevel = 1176
    Error_GuildShopLevelUpFailed_NotEnoughtGuildCoin = 1177
    Error_SelectGuildRequestItem = 1178
    Error_NotSelectGuildRequestItem = 1179
    Error_GuildSupportCountOver = 1180
    Error_ArenaCanNotResetMatchUserList = 1181
    Error_TagArenaCanNotResetMatchUserList = 1182
    Error_EnoughHeroDungeonJoinUnit = 1183
    Error_HeroDungeonNotYetClear = 1184
    Error_FiestaEventNotOpenNDayMissions = 1185
    Error_NotEnoughEventDungeonJoinCost = 1186
    Error_WorldArenaNotFullPartySlot = 1187
    Error_WorldArenaNotYetOpen = 1188
    Error_WorldArenaDoNotPlayPracticeMatch = 1189
    Error_NotEnoughWorldArenaDungeonJoinCost = 1190
    Error_AccessoryFusionNoHaveEmptySlot = 1191
    Error_DontUseAccessoryByMaterial = 1192
    Error_AccessoryFusionSlotIsEmpty = 1193
    Error_NotEnoughAccessoryStatChangeTicket = 1194
    Error_AccessorySellVaildEquipUnitUID = 1195
    Error_GuildBuyBuff = 1196
    Error_GuildEnhanceBuff = 1197
    Error_AccessroyLock = 1198
    Error_EquippedAccessroyDoNotFusion = 1199
    Error_NotEnoughWorldRaidDungeon = 1200
    Error_WorldRaidCantLeaveOnReadyState = 1201
    Error_WorldRaidCantKickYourSelf = 1202
    Error_WorldRaidCantChangeTeamUnit = 1203
    Error_WorldRaidFullUnitSlot = 1204
    Error_WorldRaidCantChangeUserSlot = 1205
    Error_WorldRaidCantCreateRoom = 1206
    Error_WorldRaidClearPreviousDungeon = 1207
    Error_NotEnoughWorldRaidRoom1 = 1220
    Error_NotEnoughWorldRaidRoom2 = 1221
    Error_NotEnoughWorldRaidRoomUser1 = 1222
    Error_NotEnoughWorldRaidRoomUser2 = 1223
    Error_NotEnoughWorldRaidRoom3 = 1224
    Error_NotEnoughWorldRaidRoomUser3 = 1225
    Error_NotEnoughWorldRaidRoomHost = 1226
    Error_ExclusiveLookItemNotEnoughMaterial = 1227
    Error_SelectBoxDontOverLimitCount = 1228
    Error_ChatChannelInvalidChannelID = 1229
    Error_ChatChannelDupChannelID = 1230
    Error_ChatChannelOutOfRangeChannelID = 1231
    Error_AlienDungeonJoinCountIsMax = 1232
    Error_AlienWorldDungeonJoinCountIsMax = 1233
    Error_NotEnoughAlienWorldDungeonTicket = 1234
    Error_DimensionGapGroupNotSelect = 1235
    Error_NotEnoughPassMissionClearCost = 1240
    Error_NotEnoughPassGachaCost = 1241
    Error_NotGetAblePassReward = 1242
    Error_NotEnoughPassGachaInitCost = 1243
    Error_LimitSaleGoodsTimeOver = 1300
    Error_UnitRarenessUpgradeNotEnoughCost = 1301
    Error_ChangeSaveEquipSet1 = 1310
    Error_GetAuthID = 1320
    Error_CheckPatchInfo = 1330
    Error_CheckServerInfo = 1331
    Error_HeartHeaterAlreadyDiedUnit = 1334
    Error_HeartHeaterUserRankNotEnough = 1335
    Error_StoryDungeonLocked = 1337
    Error_GuildWarsTeamEmptySet = 1338
    Error_GuildWarsAlreadyUsedUnit = 1339
    Error_GuildWarsPvpCleared = 1340
    Error_GuildWarsPvpProceeding = 1341
    Error_GuildwarsPvePlayed = 1342
    Error_GuildWarsNotGuildMaster = 1343
    Error_GuildWarsPvpPlayCountOver = 1344
    Error_HeartHeaterTeamSelectEmpty = 1345
    Error_GuildWarsCurrentIsNotWarSeason = 1346
    Error_GuildWarsBuffMustBeSelectTwo = 1347
    Error_GuildWarsCanNotSelectBuff = 1348
    Error_SkipGuildRaidNotYetPlayDungeon = 1349
    Error_SkipGuildRaidIngameDamageIsZero = 1350
    Error_SkipGuildRaidAlreadyClearedDungeon = 1351
    Error_OrdealNotGroupUnit = 1352
    Error_OrdealGroupPlayCountLimit = 1354
    Error_ArtifactRandomStatUpgradeNotSelectStat = 1356
    Error_ArtifactRandomStatUpgradeAlreadyMaxLevel = 1357
    Error_ArtifactRandomStatUpgradeNotYetEnhanceMaxLevel = 1358
    Error_ArtifactRandomStatUpgradeCanNotFoundArtifactOptionEnhanceInfo = 1359
    Error_ArtifactRandomStatUpgradeNotEnoughCost = 1360
    Error_CheckTierUpNotEnoughUnitGrade = 1361
    Error_HeartHeaterCurrentChapterCleared = 1364
    Error_HeartHeaterAllChapterCleared = 1365
    Error_HeartHeaterTimeOut = 1366
    Error_HeartHeaterSelectResurrectionUnit = 1368
    Error_HeartHeaterSelectNextChapter = 1369
    Error_HeartHeaterSelectDiedUnit = 1370
    Error_HeartHeaterNoHaveResurrectionUnit = 1371
    Error_NotEnoughWorldRaidDungeonJoinCost = 1372
    Error_WorldRaidClearFirstSingleDungeon = 1373
    Error_MyInfoChangeBackNotBuy = 1374
    Error_MyInfoChangeBackNotSelect = 1375
    Error_MyInfoChangeBackSendPacket = 1376
    Error_MyInfoChangeBackSameBack = 1377
    Error_ChoiceCubeNotSelectSummonUnit = 1378
    Error_ChoiceCubeAlreadySelectedUnit = 1379
    Error_ChoiceCubeCanNotFoundEventInfo = 1380
    Error_ChoiceCubeNoHaveUnit = 1381
    Error_ChoiceCubeNotEnoughHeroLevel = 1382
    Error_ChoiceCubeNoHaveSummonList = 1383
    Error_ChoiceCubeRemainSummonCountIsZero = 1384
    Error_WrongScreen = 1385
    Error_NotEnoughArtifactStatChangeTicket = 1390
    Error_ATTiOSDeviceSetDenied = 1391
    Error_ATTiOSDeviceRestricted = 1392
    Error_CheckAwakenNotUnitGradeConditionClear = 1393
    Error_CheckAwakenPrerequisitesAwakenIDNotConditionClear = 1394
    Error_UDPQueryInventoryFailed = 2389
    Error_UDPInitializedFailed = 2390
    Error_UDPPurchaseConsumeFailed = 2391
    Error_UDPPurchaseFailed = 2392
    Error_SignInFail = 2393
    Error_SignInCancel = 2394
    Error_StoreInitializeFail = 2395
    Error_UDPPurchaseCancel = 2396
    Error_UDPAlreadyPurchaseOwned = 2398
    Error_UDPAreaNotSupported = 2399
    Error_UDPNotAgreeSign = 2400
    Error_UDPAlreadyProductConsumed = 2401
    Error_CommandCenterAlreadyMaxLevel = 2403
    Error_CommandCenterCantFoundCommandCenterStatInfo = 2404
    Error_CommandCenterNotEnoughLevelUpCost = 2405
    Error_CommandCenterNotEnoughCollectionCondition = 2406
    Error_CommandersAlreadyMaxLevel = 2407
    Error_CommandersCantFoundCommandersStatInfo = 2408
    Error_CommandersNotEnoughLevelUpCost = 2409
    Error_CommandersNotEnoughCommandCenterLevel = 2410
    Error_OrdealShopTimeOut = 2411
    Error_NotEnoughCollaboDungeonJoinCost = 2412
    Error_CollaboDungeonChangeTeamUnit = 2413
    Error_CollaboDungeonSkipDamageIsZero = 2414
    Error_CollaboDungeonFakeUnitNotItemChange = 2415
    Error_ArenaAttackTeamSettingIsNotSetted = 2417
    Error_ArenaAttackSeasonTimeOver = 2418
    Error_NotEnoughArenaJoinCost = 2419
    Error_MyInfoChangeFrameSendPacket = 2420
    Error_MyInfoChangeFrameNotSelect = 2421
    Error_MyInfoChangeFrameSameProfile = 2422
    Error_MyInfoNotReleaseFrame = 2423
    Error_WithdrawConfirmWrongAccountID = 2424
    Error_FriendPointNoHaveFriendForSendRecv = 2425
    Error_NotOpenSceneCardSlot = 2426
    Error_DuplicateArtifact = 2427
    Error_GachaEventSeasonTimeout = 2429
    Error_GachaEventInitCountIsMax = 2430
    Error_GachaEventNotEnoughSSRewardGainCount = 2431
    Error_JumpingHeroEventTimeOver = 2432
    Error_AbuseArtifactDoNotEquip = 2433
    Error_AbuseArtifactDoNotUseMaterial = 2434
    Error_AbuseArtifactDoNotSell = 2435
    Error_AbuseArtifactDoNotRandomStatUpgrade = 2436
    Error_AbuseArtifactDoNotSpecialStatChange = 2437
    Error_WaveRaidCheckPartyCondition = 2438
    Error_WaveRaidDisableTime = 2439
    Error_NotEnoughtBossDungeonImmedialetyClearTicket = 2440
    Error_BossDungeonImmedialteyClearTimeCondition = 2441
    Error_GlobalArenaIngameReconnect = 2442
    Error_GlobalArenaGlobalMatchServerDisconnect = 2444
    Error_GlobalArenaWrongRoomInfo = 2445
    Error_CubeDungeonCondtion = 2446
    Error_NewBossDungeonBaseCondition = 2447

    _NAMES = {
        0: 'None',
        999: 'Error_Invisible',
        1000: 'Error_CheckTierUpNoneTierInfo',
        1001: 'Error_CheckTierUpGrade',
        1002: 'Error_CheckTierUpResource1',
        1003: 'Error_CheckTierUpResource2',
        1004: 'Error_CheckTierUpResource3',
        1005: 'Error_CheckLevelUpNoneLevelupInfo',
        1006: 'Error_CheckLevelUpResource1',
        1007: 'Error_CheckLevelUpResource2',
        1008: 'Error_CheckGradeUpNoneGradeUpInfo',
        1009: 'Error_CheckGradeUPMaxTier',
        1010: 'Error_CheckGradeUpMaxLevel',
        1011: 'Error_CheckGradeUpResource1',
        1012: 'Error_CheckGradeUpResource2',
        1013: 'Error_CheckGradeUpResource3',
        1014: 'Error_CheckAwakenNoneAwakenInfo',
        1015: 'Error_CheckAwakenResource1',
        1016: 'Error_CheckAwakenResource2',
        1017: 'Error_CheckAwakenResource3',
        1018: 'Error_CheckAwakenResource4',
        1019: 'Error_CheckAwakenResource5',
        1020: 'Error_CheckUpgradeItemNoneUpgradeItemInfo',
        1021: 'Error_CheckUpgradeItemResource1',
        1022: 'Error_CheckUpgradeItemResource2',
        1023: 'Error_CheckUpgradeItemResource3',
        1024: 'Error_CheckUpgradeItemResource4',
        1025: 'Error_CheckUpgradeItemResource5',
        1026: 'Error_CheckUpgradeItemResource6',
        1027: 'Error_CheckArtifactLevelUpNoneInfo',
        1028: 'Error_CheckArtifactTierUpNoneInfo',
        1029: 'Error_CheckArtifactTierUpLowerExp',
        1030: 'Error_CheckArtifactTierUpResource1',
        1031: 'Error_CheckArtifactTierUpResource2',
        1032: 'Error_CheckRuneGradeUpNoneGradeUpInfo',
        1033: 'Error_CheckRuneGradeUpResource1',
        1034: 'Error_CheckRuneGradeUpResource2',
        1035: 'Error_CheckRuneFixGradeUpNoneGradeUpInfo',
        1036: 'Error_CheckRuneFixGradeUpResource1',
        1037: 'Error_CheckRuneChangeNoneChangeInfo',
        1038: 'Error_CheckRuneChangeResource1',
        1039: 'Error_CheckRuneChangeResource2',
        1040: 'Error_CheckSkillBookLean',
        1041: 'Error_CheckSkillBookDontLean',
        1042: 'Error_CheckSkillBookNotLean',
        1043: 'Error_CheckSkillBookMaxGrade',
        1044: 'Error_CheckSkillBookNoneInfo',
        1045: 'Error_CheckSkillBookResource',
        1046: 'Error_CommanderMaxLevel',
        1047: 'Error_CommanderNotMaxLevel',
        1048: 'Error_CommanderNoneLevelupInfo',
        1049: 'Error_CommanderMaxTier',
        1050: 'Error_CommanderNoneTierupInfo',
        1051: 'Error_CommanderCost',
        1052: 'Error_CommanderLeanBGM',
        1053: 'Error_CommanderNotLeanBGM',
        1054: 'Error_CommanderNoneBGMInfo',
        1055: 'Error_CommanderNoneBGMLearnInfo',
        1056: 'Error_CommanderNoneBGMGradeUpInfo',
        1057: 'Error_CommanderBGMMaxGrade',
        1058: 'Error_CommanderNonePassiveInfo',
        1059: 'Error_CommanderPassiveMaxLevel',
        1060: 'Error_NotOpenDungeon',
        1061: 'Error_TimeOverDungeon',
        1062: 'Error_InvaildDungeon',
        1063: 'Error_ClearedDungeon',
        1064: 'Error_RequirePrevDungeonClear',
        1065: 'Error_LowUserRankDungeon',
        1066: 'Error_TraningTowerNotSaveCheckPoint',
        1067: 'Error_ArtifactLevelUpExpOverFlow',
        1068: 'Error_GachaClose',
        1069: 'Error_InvaildGachaInfo',
        1070: 'Error_CheckGachaResource',
        1071: 'Error_CheckTimeReduceResourceNotEnough',
        1072: 'Error_CheckTimeReduceOver',
        1073: 'ErrorRequestEnoughtUnitCount',
        1074: 'Error_CheckSellAble',
        1075: 'Error_UnitNoneSelectItem',
        1076: 'Error_FriendPointSendLackOfTime',
        1079: 'Error_ChangePartyUnchangeableUnit',
        1080: 'Error_ChangePartyLimitChangeUnit',
        1081: 'Error_ChangePartyFull',
        1082: 'Error_ChangePartyDuplicateUnit',
        1083: 'Error_NotFullParty',
        1084: 'Error_CheckGradeUpMaxGrade',
        1085: 'Error_CheckAwakenLean',
        1086: 'Error_CheckAwakenNotConditionClear',
        1087: 'Error_CheckAwakenSelectDontLean',
        1088: 'Error_CheckAwakenSelectCost',
        1089: 'Error_NotUpdate',
        1090: 'Error_GuildDonationLimitOnceDay',
        1091: 'Error_GuildDonationNotEnoughtResource',
        1092: 'Error_CheckAwakenRewardConditionNoneInfo',
        1093: 'Error_CheckAwakenRewardConditionOverIndex',
        1094: 'Error_CheckAwakenRewardConditionGetIndex',
        1095: 'Error_CheckAwakenRewardConditionDontCondition',
        1096: 'Error_CheckSceneCardLevelupNoneTargetInfo',
        1097: 'Error_CheckSceneCardLevelupNonePreMaterialInfo',
        1098: 'Error_CheckSceneCardLevelupNoneCurrentMaterialInfo',
        1099: 'Error_CheckSceneCardLevelupMaxSkillLevel',
        1100: 'Error_CheckSceneCardLevelupMaxLevel',
        1101: 'Error_CheckSceneCardLevelupGold',
        1102: 'Error_CheckSceneCardEquipSameID',
        1103: 'Error_MaterialSceneCardVaildEquipUnitUID',
        1104: 'Error_SceneCardEnhanceEmptyMaterial',
        1105: 'Error_CheckSceneCardMaxLevelOnlyDuplicateCard',
        1106: 'Warning_CheckSceneCardMaxSkillLevelAddDuplicateCard',
        1107: 'Error_CheckSceneCardEquipNoneInfo',
        1108: 'Error_CheckSceneCardEquipCondition',
        1109: 'Error_CheckSceneCardEquipUsed',
        1110: 'Error_CheckSceneCardLevelupEquip',
        1111: 'Error_CheckSceneCardEquipSlot',
        1112: 'Error_MyInfoChangeProfileSendPacket',
        1113: 'Error_MyInfoChangeProfileNotSelect',
        1114: 'Error_MyInfoChangeProfileSameProfile',
        1115: 'Error_MyInfoChangeNickNameCost',
        1116: 'Error_MyInfoChangeNickNameLength',
        1117: 'Error_TrainingTowerJoinCount0',
        1118: 'Error_CheckGradeUpNotNextGrade',
        1119: 'Error_CheckLevelUpUserRank',
        1120: 'Error_SummonHeroPieceNotEnough',
        1121: 'Error_PerchasingGetPerchasingInfo',
        1122: 'Error_PerchasingnotAvailableForpurChase',
        1123: 'Error_PerchasingInitialized',
        1128: 'Error_NotPieceDecompositionEnoughtResource',
        1129: 'Error_EtcSellNotEnoughResource',
        1130: 'Error_NotWeaponSellEnoughResource',
        1131: 'Error_PremiumHeroSummonNotEnoughResource',
        1132: 'Error_InvaildHeroPieceSummon',
        1133: 'PackmanResetNotEnoughCost',
        1134: 'PackmanLevelUpNotEnoughCost',
        1135: 'NotEnoughNPCRequestRenew',
        1137: 'NotEnoughHeroDungeonJoinCost',
        1138: 'NotEnoughTrainingTowerDungeonJoinCost',
        1139: 'Error_NotEnoughDimensionGachaInstantCost',
        1140: 'NotEnoughAlienDungeonJoinCost',
        1141: 'NotEnoughAlienDungeonTicket',
        1142: 'GuildRaidOnlyGuildMasterCanOpen',
        1143: 'GuildRaidOnlyGuildMasterCanReOpen',
        1144: 'Error_CheckSceneCardEquipConditionFailUnitForce',
        1145: 'Error_CheckSceneCardEquipConditionFailUnitClass',
        1146: 'Error_CheckSceneCardEquipConditionFailUnitGrade',
        1147: 'Error_CheckSceneCardEquipConditionFailUnitType',
        1148: 'Error_CheckSceneCardEquipConditionFailUnitID',
        1149: 'Error_PerchasingProgress',
        1150: 'Error_CheckGuildRaidNotEnoughtTicket',
        1151: 'Error_SceneCardEnhanceFull10Material',
        1152: 'EventSceneCardMaximunTrade',
        1153: 'EventSceneCardNotEnoughtCost',
        1154: 'Error_SceneCardSellVaildEquipUnitUID',
        1155: 'NotEnoughOrdealDungeonJoinCost',
        1156: 'Error_SelectOrdealDugenonStage',
        1157: 'Error_RequirePreOrdealDungeonClear',
        1158: 'Error_SelectPreOrdealDugenonStage',
        1159: 'Error_MaterialArtifactVaildEquipUnitUID',
        1160: 'Error_ArtifactEnhanceFull10Material',
        1161: 'Error_ArtifactSellVaildEquipUnitUID',
        1162: 'Error_WaitRewardNotOngoingOrdealDungeon',
        1163: 'Error_ArtifactEnhanceMaxLevelOverExp',
        1164: 'Error_GetWaitRewardAfterReceiveClearReward',
        1165: 'Error_NotEnoughtBossDungeonTicket',
        1166: 'Error_CheckSceneCardEquipConditionFailElement',
        1167: 'Error_SelectMaterialArtifact',
        1168: 'Error_CloseGoods',
        1169: 'Error_RequirePreBossDungeonClear',
        1170: 'Error_NotEnoughtStoryDungeonJoinCost',
        1171: 'Error_NotEnoughMedalPoint',
        1172: 'ErrorTagArenaEmptyParty',
        1173: 'Error_BossArtifactNotEnoughtCost',
        1174: 'Error_DuplicateHeroExtiatParties',
        1175: 'Error_GuildShopAlreadyMaxLevel',
        1176: 'Error_GuildShopLevelUpFailed_LowGuildLevel',
        1177: 'Error_GuildShopLevelUpFailed_NotEnoughtGuildCoin',
        1178: 'Error_SelectGuildRequestItem',
        1179: 'Error_NotSelectGuildRequestItem',
        1180: 'Error_GuildSupportCountOver',
        1181: 'Error_ArenaCanNotResetMatchUserList',
        1182: 'Error_TagArenaCanNotResetMatchUserList',
        1183: 'Error_EnoughHeroDungeonJoinUnit',
        1184: 'Error_HeroDungeonNotYetClear',
        1185: 'Error_FiestaEventNotOpenNDayMissions',
        1186: 'Error_NotEnoughEventDungeonJoinCost',
        1187: 'Error_WorldArenaNotFullPartySlot',
        1188: 'Error_WorldArenaNotYetOpen',
        1189: 'Error_WorldArenaDoNotPlayPracticeMatch',
        1190: 'Error_NotEnoughWorldArenaDungeonJoinCost',
        1191: 'Error_AccessoryFusionNoHaveEmptySlot',
        1192: 'Error_DontUseAccessoryByMaterial',
        1193: 'Error_AccessoryFusionSlotIsEmpty',
        1194: 'Error_NotEnoughAccessoryStatChangeTicket',
        1195: 'Error_AccessorySellVaildEquipUnitUID',
        1196: 'Error_GuildBuyBuff',
        1197: 'Error_GuildEnhanceBuff',
        1198: 'Error_AccessroyLock',
        1199: 'Error_EquippedAccessroyDoNotFusion',
        1200: 'Error_NotEnoughWorldRaidDungeon',
        1201: 'Error_WorldRaidCantLeaveOnReadyState',
        1202: 'Error_WorldRaidCantKickYourSelf',
        1203: 'Error_WorldRaidCantChangeTeamUnit',
        1204: 'Error_WorldRaidFullUnitSlot',
        1205: 'Error_WorldRaidCantChangeUserSlot',
        1206: 'Error_WorldRaidCantCreateRoom',
        1207: 'Error_WorldRaidClearPreviousDungeon',
        1220: 'Error_NotEnoughWorldRaidRoom1',
        1221: 'Error_NotEnoughWorldRaidRoom2',
        1222: 'Error_NotEnoughWorldRaidRoomUser1',
        1223: 'Error_NotEnoughWorldRaidRoomUser2',
        1224: 'Error_NotEnoughWorldRaidRoom3',
        1225: 'Error_NotEnoughWorldRaidRoomUser3',
        1226: 'Error_NotEnoughWorldRaidRoomHost',
        1227: 'Error_ExclusiveLookItemNotEnoughMaterial',
        1228: 'Error_SelectBoxDontOverLimitCount',
        1229: 'Error_ChatChannelInvalidChannelID',
        1230: 'Error_ChatChannelDupChannelID',
        1231: 'Error_ChatChannelOutOfRangeChannelID',
        1232: 'Error_AlienDungeonJoinCountIsMax',
        1233: 'Error_AlienWorldDungeonJoinCountIsMax',
        1234: 'Error_NotEnoughAlienWorldDungeonTicket',
        1235: 'Error_DimensionGapGroupNotSelect',
        1240: 'Error_NotEnoughPassMissionClearCost',
        1241: 'Error_NotEnoughPassGachaCost',
        1242: 'Error_NotGetAblePassReward',
        1243: 'Error_NotEnoughPassGachaInitCost',
        1300: 'Error_LimitSaleGoodsTimeOver',
        1301: 'Error_UnitRarenessUpgradeNotEnoughCost',
        1310: 'Error_ChangeSaveEquipSet1',
        1320: 'Error_GetAuthID',
        1330: 'Error_CheckPatchInfo',
        1331: 'Error_CheckServerInfo',
        1334: 'Error_HeartHeaterAlreadyDiedUnit',
        1335: 'Error_HeartHeaterUserRankNotEnough',
        1337: 'Error_StoryDungeonLocked',
        1338: 'Error_GuildWarsTeamEmptySet',
        1339: 'Error_GuildWarsAlreadyUsedUnit',
        1340: 'Error_GuildWarsPvpCleared',
        1341: 'Error_GuildWarsPvpProceeding',
        1342: 'Error_GuildwarsPvePlayed',
        1343: 'Error_GuildWarsNotGuildMaster',
        1344: 'Error_GuildWarsPvpPlayCountOver',
        1345: 'Error_HeartHeaterTeamSelectEmpty',
        1346: 'Error_GuildWarsCurrentIsNotWarSeason',
        1347: 'Error_GuildWarsBuffMustBeSelectTwo',
        1348: 'Error_GuildWarsCanNotSelectBuff',
        1349: 'Error_SkipGuildRaidNotYetPlayDungeon',
        1350: 'Error_SkipGuildRaidIngameDamageIsZero',
        1351: 'Error_SkipGuildRaidAlreadyClearedDungeon',
        1352: 'Error_OrdealNotGroupUnit',
        1354: 'Error_OrdealGroupPlayCountLimit',
        1356: 'Error_ArtifactRandomStatUpgradeNotSelectStat',
        1357: 'Error_ArtifactRandomStatUpgradeAlreadyMaxLevel',
        1358: 'Error_ArtifactRandomStatUpgradeNotYetEnhanceMaxLevel',
        1359: 'Error_ArtifactRandomStatUpgradeCanNotFoundArtifactOptionEnhanceInfo',
        1360: 'Error_ArtifactRandomStatUpgradeNotEnoughCost',
        1361: 'Error_CheckTierUpNotEnoughUnitGrade',
        1364: 'Error_HeartHeaterCurrentChapterCleared',
        1365: 'Error_HeartHeaterAllChapterCleared',
        1366: 'Error_HeartHeaterTimeOut',
        1368: 'Error_HeartHeaterSelectResurrectionUnit',
        1369: 'Error_HeartHeaterSelectNextChapter',
        1370: 'Error_HeartHeaterSelectDiedUnit',
        1371: 'Error_HeartHeaterNoHaveResurrectionUnit',
        1372: 'Error_NotEnoughWorldRaidDungeonJoinCost',
        1373: 'Error_WorldRaidClearFirstSingleDungeon',
        1374: 'Error_MyInfoChangeBackNotBuy',
        1375: 'Error_MyInfoChangeBackNotSelect',
        1376: 'Error_MyInfoChangeBackSendPacket',
        1377: 'Error_MyInfoChangeBackSameBack',
        1378: 'Error_ChoiceCubeNotSelectSummonUnit',
        1379: 'Error_ChoiceCubeAlreadySelectedUnit',
        1380: 'Error_ChoiceCubeCanNotFoundEventInfo',
        1381: 'Error_ChoiceCubeNoHaveUnit',
        1382: 'Error_ChoiceCubeNotEnoughHeroLevel',
        1383: 'Error_ChoiceCubeNoHaveSummonList',
        1384: 'Error_ChoiceCubeRemainSummonCountIsZero',
        1385: 'Error_WrongScreen',
        1390: 'Error_NotEnoughArtifactStatChangeTicket',
        1391: 'Error_ATTiOSDeviceSetDenied',
        1392: 'Error_ATTiOSDeviceRestricted',
        1393: 'Error_CheckAwakenNotUnitGradeConditionClear',
        1394: 'Error_CheckAwakenPrerequisitesAwakenIDNotConditionClear',
        2389: 'Error_UDPQueryInventoryFailed',
        2390: 'Error_UDPInitializedFailed',
        2391: 'Error_UDPPurchaseConsumeFailed',
        2392: 'Error_UDPPurchaseFailed',
        2393: 'Error_SignInFail',
        2394: 'Error_SignInCancel',
        2395: 'Error_StoreInitializeFail',
        2396: 'Error_UDPPurchaseCancel',
        2398: 'Error_UDPAlreadyPurchaseOwned',
        2399: 'Error_UDPAreaNotSupported',
        2400: 'Error_UDPNotAgreeSign',
        2401: 'Error_UDPAlreadyProductConsumed',
        2403: 'Error_CommandCenterAlreadyMaxLevel',
        2404: 'Error_CommandCenterCantFoundCommandCenterStatInfo',
        2405: 'Error_CommandCenterNotEnoughLevelUpCost',
        2406: 'Error_CommandCenterNotEnoughCollectionCondition',
        2407: 'Error_CommandersAlreadyMaxLevel',
        2408: 'Error_CommandersCantFoundCommandersStatInfo',
        2409: 'Error_CommandersNotEnoughLevelUpCost',
        2410: 'Error_CommandersNotEnoughCommandCenterLevel',
        2411: 'Error_OrdealShopTimeOut',
        2412: 'Error_NotEnoughCollaboDungeonJoinCost',
        2413: 'Error_CollaboDungeonChangeTeamUnit',
        2414: 'Error_CollaboDungeonSkipDamageIsZero',
        2415: 'Error_CollaboDungeonFakeUnitNotItemChange',
        2417: 'Error_ArenaAttackTeamSettingIsNotSetted',
        2418: 'Error_ArenaAttackSeasonTimeOver',
        2419: 'Error_NotEnoughArenaJoinCost',
        2420: 'Error_MyInfoChangeFrameSendPacket',
        2421: 'Error_MyInfoChangeFrameNotSelect',
        2422: 'Error_MyInfoChangeFrameSameProfile',
        2423: 'Error_MyInfoNotReleaseFrame',
        2424: 'Error_WithdrawConfirmWrongAccountID',
        2425: 'Error_FriendPointNoHaveFriendForSendRecv',
        2426: 'Error_NotOpenSceneCardSlot',
        2427: 'Error_DuplicateArtifact',
        2429: 'Error_GachaEventSeasonTimeout',
        2430: 'Error_GachaEventInitCountIsMax',
        2431: 'Error_GachaEventNotEnoughSSRewardGainCount',
        2432: 'Error_JumpingHeroEventTimeOver',
        2433: 'Error_AbuseArtifactDoNotEquip',
        2434: 'Error_AbuseArtifactDoNotUseMaterial',
        2435: 'Error_AbuseArtifactDoNotSell',
        2436: 'Error_AbuseArtifactDoNotRandomStatUpgrade',
        2437: 'Error_AbuseArtifactDoNotSpecialStatChange',
        2438: 'Error_WaveRaidCheckPartyCondition',
        2439: 'Error_WaveRaidDisableTime',
        2440: 'Error_NotEnoughtBossDungeonImmedialetyClearTicket',
        2441: 'Error_BossDungeonImmedialteyClearTimeCondition',
        2442: 'Error_GlobalArenaIngameReconnect',
        2444: 'Error_GlobalArenaGlobalMatchServerDisconnect',
        2445: 'Error_GlobalArenaWrongRoomInfo',
        2446: 'Error_CubeDungeonCondtion',
        2447: 'Error_NewBossDungeonBaseCondition',
    }

    @classmethod
    def name(cls, v):
        return cls._NAMES.get(v, str(v))


class CollectionType(object):
    DungeonClearCount = 0
    AutoPlayRewardCount = 1
    ItemGradeUpCount = 2
    FriendPointSendCount = 3
    HeroDungeonClearCount = 4
    RoguelikePointClearCount = 5
    GetUnitCount = 6
    AlienBossDetectCount = 7
    AlienBossClearCount = 8
    GachaOpenCount = 9
    SceneCardGetCount = 10
    ArenaTierUpCount = 11
    RankupCount = 12
    ContentsPlayCount = 13
    ContentsClearCount = 14
    SceneCardGradeGetCount = 15
    ArtifactGradeGetCount = 16
    UnitGradeGetCount = 17
    TagArenaTierUpCount = 18
    GuildAttendanceCount = 19
    GuildDonationCount = 20
    SupportGuildResource = 21
    ArenaAttackWinPoint = 22
    BossDungeonGroupIDCount = 23
    WorldArenaTierUpCount = 24
    WorldArenaPlayPoint = 25
    ResourceUseValue = 26
    Event1013MissionAllClearReward = 28
    NormalDungeonStarCount = 29
    HardDungeonStarCount = 30
    NormalDungeonFloorReward = 31
    HardDungeonFloorReward = 32
    ResourceAddValue = 33
    AttendanceCount = 34
    GachaGetRarenessUnitCount = 35
    AccumulateBuyCash = 36
    UnitLevelUp = 37
    GoodsUIDBuyCount = 38
    RequestGroupCompleteCount = 39
    SceneCardGradeRecvCount = 40
    ArtifactGradeRecvCount = 41
    ItemGradeRecvCount = 42
    AwakenPartsSlotOpenCount = 43
    TagArenaAttackWinPoint = 44
    UnitRareness = 45
    ConnectSocialAccount = 46
    HeartHeaterChapterClear = 47
    WorldRaidMaxKillCount = 48
    WorldRaidMultiplayClearCount = 49
    EventViewCount = 50
    MissionClearCount = 51
    AllUnitLevelUpCount = 52
    TotalDamageRewardCount = 53
    GachaGetSpecificUnitCount = 54
    CollectionType_HighestWaveRaidScore = 55
    GlobalArenaPlayPoint = 56
    ChoiceSceneCardEventCount = 57
    DungeonGetRewardCount = 58
    ArtifactLvUpCount = 59
    HighestWaveRaid2Score = 60

    _NAMES = {
        0: 'DungeonClearCount',
        1: 'AutoPlayRewardCount',
        2: 'ItemGradeUpCount',
        3: 'FriendPointSendCount',
        4: 'HeroDungeonClearCount',
        5: 'RoguelikePointClearCount',
        6: 'GetUnitCount',
        7: 'AlienBossDetectCount',
        8: 'AlienBossClearCount',
        9: 'GachaOpenCount',
        10: 'SceneCardGetCount',
        11: 'ArenaTierUpCount',
        12: 'RankupCount',
        13: 'ContentsPlayCount',
        14: 'ContentsClearCount',
        15: 'SceneCardGradeGetCount',
        16: 'ArtifactGradeGetCount',
        17: 'UnitGradeGetCount',
        18: 'TagArenaTierUpCount',
        19: 'GuildAttendanceCount',
        20: 'GuildDonationCount',
        21: 'SupportGuildResource',
        22: 'ArenaAttackWinPoint',
        23: 'BossDungeonGroupIDCount',
        24: 'WorldArenaTierUpCount',
        25: 'WorldArenaPlayPoint',
        26: 'ResourceUseValue',
        28: 'Event1013MissionAllClearReward',
        29: 'NormalDungeonStarCount',
        30: 'HardDungeonStarCount',
        31: 'NormalDungeonFloorReward',
        32: 'HardDungeonFloorReward',
        33: 'ResourceAddValue',
        34: 'AttendanceCount',
        35: 'GachaGetRarenessUnitCount',
        36: 'AccumulateBuyCash',
        37: 'UnitLevelUp',
        38: 'GoodsUIDBuyCount',
        39: 'RequestGroupCompleteCount',
        40: 'SceneCardGradeRecvCount',
        41: 'ArtifactGradeRecvCount',
        42: 'ItemGradeRecvCount',
        43: 'AwakenPartsSlotOpenCount',
        44: 'TagArenaAttackWinPoint',
        45: 'UnitRareness',
        46: 'ConnectSocialAccount',
        47: 'HeartHeaterChapterClear',
        48: 'WorldRaidMaxKillCount',
        49: 'WorldRaidMultiplayClearCount',
        50: 'EventViewCount',
        51: 'MissionClearCount',
        52: 'AllUnitLevelUpCount',
        53: 'TotalDamageRewardCount',
        54: 'GachaGetSpecificUnitCount',
        55: 'CollectionType_HighestWaveRaidScore',
        56: 'GlobalArenaPlayPoint',
        57: 'ChoiceSceneCardEventCount',
        58: 'DungeonGetRewardCount',
        59: 'ArtifactLvUpCount',
        60: 'HighestWaveRaid2Score',
    }

    @classmethod
    def name(cls, v):
        return cls._NAMES.get(v, str(v))
