"""Regenerate hc/game/enums.py from the client's own enums.

Il2CppDumper writes every enum out with its real names and values, so there is
no reason to hand-copy them. Add a name to WANT and re-run.

    python tools/gen_enums.py

Names that clash with Python keywords (`None`, `True`, ...) get a trailing
underscore; `name()` still gives you the original spelling back.
"""
import argparse
import io
import keyword
import os
import re
import sys

WANT = [
    'ResourceType',      # what a reward/cost is (Gold, Item, Shards, ...)
    'CollectionType',    # the counter system -- stage clears live here
    'ClearType',         # how a stage was played, NOT whether it was won
    'NMError',           # the client's own error codes, for Ack `Error` fields
    'MissionClearType',
    'SceneType',
]

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DUMP = os.path.join(HERE, '..', '..', 'server-research', 'dump.cs')
DEFAULT_OUT = os.path.join(HERE, '..', 'hc', 'game', 'enums.py')


def safe(name):
    return name + '_' if keyword.iskeyword(name) or name in ('None', 'True', 'False') else name


def emit(lines, want):
    out = io.StringIO()
    out.write('"""Enums lifted verbatim from the client (Il2CppDumper output).\n\n'
              'Generated by tools/gen_enums.py -- do not edit by hand.\n'
              'Names colliding with Python keywords get a trailing underscore;\n'
              '``name()`` still reports the original client spelling.\n"""\n')
    found = []
    for i, ln in enumerate(lines):
        m = re.match(r'^public enum (\w+) //', ln)
        if not m or m.group(1) not in want or m.group(1) in found:
            continue
        name = m.group(1)
        body = []
        for ln2 in lines[i + 1:i + 4000]:
            if ln2.startswith('}'):
                break
            cm = re.match(r'\s*public const \w+ (\w+) = (-?\d+);', ln2)
            if cm:
                body.append((cm.group(1), int(cm.group(2))))
        if not body:
            continue
        found.append(name)
        out.write('\n\nclass %s(object):\n' % name)
        for k, v in body:
            out.write('    %s = %d\n' % (safe(k), v))
        out.write('\n    _NAMES = {\n')
        seen = set()
        for k, v in body:
            if v not in seen:
                out.write('        %d: %r,\n' % (v, k))
                seen.add(v)
        out.write('    }\n\n    @classmethod\n    def name(cls, v):\n'
                  '        return cls._NAMES.get(v, str(v))\n')
    return out.getvalue(), found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dump', default=DEFAULT_DUMP, help='path to dump.cs')
    ap.add_argument('-o', '--out', default=DEFAULT_OUT)
    args = ap.parse_args()

    if not os.path.exists(args.dump):
        sys.exit('dump.cs not found at %s' % args.dump)
    lines = open(args.dump, encoding='utf-8', errors='replace').read().split('\n')
    text, found = emit(lines, set(WANT))
    open(args.out, 'w', encoding='utf-8').write(text)
    print('wrote %s' % args.out)
    print('enums: %s' % ', '.join(found))
    missing = [w for w in WANT if w not in found]
    if missing:
        print('not found in dump.cs: %s' % ', '.join(missing))


if __name__ == '__main__':
    main()
